package com.vsc.dataGenerator.model;

public enum ColumnType  {
    ADDRESS, AGE, CELL_PHONE, CITY, COMPANY_NAME, COUNTRY, CREDIT_CARD_NUMBER, CREDIT_CARD_TYPE, CURRENT_SYS_TIME, DATA_TIME, DATE,
    DOUBLE, E_MAIL, FIRST_NAME, FULL_NAME, GENDER, INDUSTRY, INTEGER, LAST_NAME, NAME,
    PHONE_NUMBER, SSN, STATE, TIME_STAMP, TIME_ZONE, UNIVERSITY, YEAR, ZIP_CODE, DEPARTMENT,
    HOSPITAL,DISEASE,SYMPTOMS,MEDICINE


}
